__author__ = 'hieutran'

##### System auth token #####
SYS_TOKEN_REQUIRED = -1
SYS_TOKEN_EMPTY_OR_INVALID = -2
SYS_TOKEN_EXPIRED = -3
SYS_ACCOUNT_BLOCKED = -4

##### General code #####
SUCCESSFUL = 0
MISSING_REQUIRED_FIELD = 1
TOKEN_REQUIRED = 2
TOKEN_EMPTY_OR_INVALID = 3
TOKEN_EXPIRED = 4
METHOD_NOT_SUPPORT = 5
EMAIL_INVALID = 6
URL_INVALID = 7
SERVER_ERROR = 99

##### Account error code #####
ACCOUNT_BLOCKED = 100
EMAIL_EXISTED = 101
PASSWORD_INVALID = 102
NAME_FORMAT = 103
ACCOUNT_ACTIVATED = 104
